import type { CopilotInsights, CustomerProfile } from '../types'
import { AGENT_NAME } from '../brand'

const esc = (s: unknown) =>
  String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] as string)

/** Builds a one-page brief and opens the browser's print dialog ("Save as PDF") in a hidden frame. */
export function printMeetingBrief(profile: CustomerProfile | null, copilot: CopilotInsights | null) {
  const p = profile ?? {}
  const c = copilot
  const facts: [string, unknown][] = [
    ['Name', p.customerName],
    ['Age', p.age],
    ['Occupation', p.occupation],
    ['Income band', p.incomeBand],
    ['Dependents', p.dependents],
    ['Budget', p.budgetNotes],
  ]
  const list = (items: string[] | undefined) =>
    items && items.length ? `<ul>${items.map((i) => `<li>${esc(i)}</li>`).join('')}</ul>` : '<p class="muted">None captured</p>'

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>AIA Voice Insights — Meeting Brief</title>
<style>
  body{font:13px/1.5 -apple-system,'Segoe UI',Helvetica,Arial,sans-serif;color:#14161f;margin:36px}
  h1{font-size:22px;margin:0} h2{font-size:12px;letter-spacing:.06em;text-transform:uppercase;color:#d31145;margin:22px 0 8px;border-bottom:1px solid #eee;padding-bottom:4px}
  .sub{color:#666;margin:2px 0 0} .bar{height:4px;background:#d31145;margin-bottom:18px;border-radius:2px}
  table{border-collapse:collapse;width:100%} td{padding:4px 0;vertical-align:top} td:first-child{color:#666;width:130px}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:0 28px} ul{margin:4px 0;padding-left:18px} .muted{color:#999}
  .pill{display:inline-block;padding:2px 10px;border-radius:99px;background:#fdeaf0;color:#d31145;font-weight:600;margin-right:6px}
  .prod{margin:6px 0;padding:8px 10px;border:1px solid #eee;border-radius:8px} .prod b{font-size:13px} .ev{color:#555;font-style:italic;margin:3px 0 0}
  .flag{border-left:3px solid #d31145;padding:4px 10px;margin:6px 0;background:#fff5f8} .ok{color:#15803d;font-weight:600}
  footer{margin-top:28px;color:#999;font-size:11px}
</style></head><body>
<div class="bar"></div>
<h1>Customer Meeting Brief</h1>
<p class="sub">AIA Voice Insights · ${esc(new Date().toLocaleString())}</p>
<p class="sub" style="color:#b45309"><b>Preliminary — live view.</b> Based on real-time signals during the call. The full agent analysis and sales report are the final recommendation.</p>

<h2>Customer profile</h2>
<table>${facts.filter(([, v]) => v !== null && v !== undefined && v !== '').map(([k, v]) => `<tr><td>${k}</td><td>${esc(v)}</td></tr>`).join('') || '<tr><td class="muted">No fields captured</td></tr>'}</table>
<div class="grid"><div><h2>Goals &amp; concerns</h2>${list(p.goalsAndConcerns)}</div><div><h2>Existing policies</h2>${list(p.existingPolicies)}</div></div>

${
  c
    ? `<h2>Customer signals</h2>
<p><span class="pill">Sentiment: ${esc(c.sentiment.label)} (${esc(c.sentiment.emotion)})</span><span class="pill">Buying signal: ${esc(c.buyingSignal.level)} · ${c.buyingSignal.score}/100</span></p>
${c.buyingSignal.signals.length ? `<ul>${c.buyingSignal.signals.map((s) => `<li>${esc(s)}</li>`).join('')}</ul>` : ''}
<h2>Detected needs</h2>${c.needs.length ? `<p>${c.needs.map((n) => `<span class="pill">${esc(n.label)} · ${n.strength}%</span>`).join('')}</p>` : '<p class="muted">None detected</p>'}
<h2>Product matches</h2>${c.productMatches.length ? c.productMatches.map((m) => `<div class="prod"><b>${esc(m.productName)}</b> — fit ${m.fitScore}/100<p class="ev">“${esc(m.evidence)}”</p><span class="muted">${esc(m.source)}</span></div>`).join('') : '<p class="muted">No matches</p>'}
<h2>Compliance checklist</h2>${c.complianceFlags.length ? c.complianceFlags.map((f) => `<div class="flag"><b>${esc(f.severity === 'high' ? 'High risk' : 'Caution')}:</b> “${esc(f.statement)}”<br>${esc(f.advice)}</div>`).join('') : '<p class="ok">✓ No risky statements detected during the conversation</p>'}
<h2>Suggested follow-ups</h2>${list(c.nextQuestions)}`
    : ''
}
<footer>Generated by AIA Voice Insights with ${AGENT_NAME}. AI-assisted summary — advisor review required before any customer communication.</footer>
</body></html>`

  const frame = document.createElement('iframe')
  frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0'
  document.body.appendChild(frame)
  const doc = frame.contentDocument
  if (!doc) return
  doc.open()
  doc.write(html)
  doc.close()
  // Small delay lets the frame lay out before the print dialog snapshots it.
  setTimeout(() => {
    frame.contentWindow?.focus()
    frame.contentWindow?.print()
    setTimeout(() => frame.remove(), 60000)
  }, 300)
}
